# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings 

use_default_settings: true 
server: 
   secret_key: "mysecretkey" # change this! 
   limiter: false 
   image_proxy: true 
   port: 8080 
   bind_address: "0.0.0.0" 

ui: 
   static_use_hash: true 

search:
   safe_search: 0
   autocomplete: ""
   autocomplete_min: 4
   favicon_resolver: ""
   default_lang: "auto"

   formats:
     - html
     - json
